# Site settings
title: Andrew Burkus
email: andrew@burkus.xyz
description: > # this means to ignore newlines until "baseurl:"
  a blog about programming, tech, and such.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "burkus.github.io/" # the base hostname & protocol for your site
twitter_username: AndrewBurkus
github_username:  burkus

# Build settings
markdown: kramdown
destination: "./build"
